### PR TITLE
Add installation instructions for Homebrew

### PR DESCRIPTION
**Pull request by jawshooah**
Pending merge of Homebrew/homebrew#37852

### CODE REVIEW

**Comment by yyuu** [comment]
Thanks for PR :octocat: Although, as I've added notice in README before (b10f90ed913e7f70f1677f3e317c86f192ae3bc4), starts from pyenv v20141211, it bundles built-in auto-rehash feature as same as `pyenv-pip-rehash`. Basically we don't need this plugin other than the purpose of backward compatibility.

https://github.com/yyuu/pyenv/blob/e9aa6cf649673e7de416ef7346be19501d096cb1/CHANGELOG.md#20141211

**Comment by jawshooah** [comment]
Ah, whoops! Sorry about that. Perhaps it's still useful for those using an older version of pyenv?

**Comment by yyuu** [comment]
It would be useful for the people who are still using pyenv older than v20141211.

**Comment by jawshooah** [comment]
Cool. So it is worth merging this in since the deprecation is already mentioned elsewhere in the README?

I'll add a caveat mentioning the deprecation in the Homebrew formula as well.

**Comment by yyuu** [comment]
I'll merge this once Homebrew/homebrew#37852 has been merged.

**Comment by jawshooah** [comment]
Whoops, seems I didn't do my homework before submitting. This is already available in [homebrew-boneyard](https://github.com/Homebrew/homebrew-boneyard/pull/37). I've updated the instructions accordingly.

**Pull request merged**
